# Generated by Django 5.1.4 on 2024-12-18 17:54

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=256)),
                ('mail', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('role', models.CharField(choices=[('Student', 'Student'), ('CA', 'CA'), ('Professional', 'Professional'), ('Contingent', 'Contingent '), ('Startup', 'Startup')], max_length=24)),
                ('payment_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insti', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('dept', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.users')),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=256)),
                ('industry', models.CharField(max_length=256)),
                ('year_of_establishment', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)])),
                ('stage_of_startup', models.CharField(choices=[('Preseed', 'Preseed'), ('Seed', 'Seed'), ('Funding', 'Funding')], max_length=100)),
                ('if_ic', models.BooleanField(default=True)),
                ('cofounders', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.users')),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proffession', models.CharField(max_length=256)),
                ('industry', models.CharField(max_length=256)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('curr_org', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.users')),
            ],
        ),
        migrations.CreateModel(
            name='Contingent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insti', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('no_of_people', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.users')),
            ],
        ),
        migrations.CreateModel(
            name='CA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insti', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('dept', models.CharField(max_length=256)),
                ('no_of_regs', models.PositiveIntegerField()),
                ('link', models.URLField()),
                ('referral_code', models.CharField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.users')),
            ],
        ),
    ]
