# Generated by Django 5.1.4 on 2024-12-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
    ]
