# Generated by Django 5.1.4 on 2024-12-19 06:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_users_mail_remove_users_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ca_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='ca',
            name='referral_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
