# Generated by Django 5.1.4 on 2025-01-03 05:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_users_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ca',
            name='no_of_regs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ca',
            name='referral_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
