# Generated by Django 5.1.4 on 2025-01-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_ca_link_alter_ca_no_of_regs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='referral_code',
            field=models.CharField(default='a0a4', editable=False, max_length=4, unique=True),
        ),
    ]
