# Generated by Django 5.1.4 on 2025-01-03 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_ca_referral_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ca',
            name='registered_users',
            field=models.ManyToManyField(default=None, related_name='referral_cas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ca',
            name='target_regs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ca',
            name='referral_code',
            field=models.CharField(default='0a02', max_length=4, unique=True),
        ),
    ]
