# Generated by Django 5.1.4 on 2025-01-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_ca_registered_users_ca_target_regs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='no_of_regs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ca',
            name='referral_code',
            field=models.CharField(default='74cc', max_length=4, unique=True),
        ),
    ]
