# Generated by Django 5.1.4 on 2025-01-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_ca_no_of_regs_alter_ca_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='referral_code',
            field=models.CharField(default='a0a5', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='ca',
            name='registered_users',
            field=models.ManyToManyField(default=None, related_name='referral_cas', to='portal.users'),
        ),
    ]
