# Generated by Django 5.1.4 on 2025-01-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_alter_ca_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='referral_code',
            field=models.CharField(default='d451', max_length=4, unique=True),
        ),
    ]
