# Generated by Django 5.1.4 on 2025-01-22 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_alter_ca_referral_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='GES_Participants',
        ),
        migrations.AlterField(
            model_name='ca',
            name='referral_code',
            field=models.CharField(default='2972', max_length=4, unique=True),
        ),
    ]
