# Generated by Django 5.1.4 on 2025-01-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_rename_users_ges_participants_alter_ca_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='referral_code',
            field=models.CharField(default='5e67', max_length=4, unique=True),
        ),
    ]
