# Generated by Django 5.1.4 on 2025-01-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_rename_ges_participants_users_alter_ca_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='shirt_size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='ca',
            name='referral_code',
            field=models.CharField(default='c82d', max_length=4, unique=True),
        ),
    ]
