# Generated by Django 5.1.4 on 2025-01-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_users_arrival_date_users_departure_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='referral_code',
            field=models.CharField(default='a602', max_length=4, unique=True),
        ),
    ]
