# Generated by Django 5.1.4 on 2025-01-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_alter_ca_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ges_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='ca',
            name='referral_code',
            field=models.CharField(default='65f2', max_length=4, unique=True),
        ),
    ]
