# Generated by Django 5.1.4 on 2025-01-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_alter_ca_referral_code_alter_users_ges_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='referral_code',
            field=models.CharField(default='502c', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='ges_id',
            field=models.CharField(blank=True, default='GES2578', max_length=10, unique=True),
        ),
    ]
