# Generated by Django 5.1.4 on 2025-01-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0040_alter_ca_referral_code_alter_users_ges_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ca',
            name='target_regs',
        ),
        migrations.AlterField(
            model_name='ca',
            name='referral_code',
            field=models.CharField(default='10d7', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='ges_id',
            field=models.CharField(blank=True, default='GESC719', max_length=10, unique=True),
        ),
    ]
