# Generated by Django 5.1.4 on 2025-01-28 13:47

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0044_alter_ca_referral_code_alter_users_ges_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='referral_code',
            field=models.CharField(default=portal.models.CA.create_referral_code, max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='ges_id',
            field=models.CharField(blank=True, default=portal.models.Users.create_ges_id, max_length=10, unique=True),
        ),
    ]
